Allow custom pager support in patronictl edit-config
zalando/patroni pull request #1696
Opened 2020-09-15 11:50 UTC by pashagolub

Adds the possibility for `patronictl edit-config` custom pager support.

Fixes #1695 

Mentioned in [patroni-windows-packaging #16](https://github.com/cybertec-postgresql/patroni-windows-packaging/issues/16)

2020-09-15 12:20 UTC, CyberDem0n requested changes

2020-09-15 12:20 UTC, CyberDem0n commented on patroni/ctl.py
> +            pager = 'more.com' if (sys.platform == 'win32') else None
```suggestion
            if not find_executable('less'):
                pager = 'more.com' if sys.platform == 'win32' else 'more'
```

2020-09-15 12:20 UTC, CyberDem0n commented on patroni/ctl.py
> +import ydiff
```suggestion
try:
    import ydiff
except ImportError:
    import cdiff as ydiff
```

And please move it after the line with `import yaml`

2020-09-15 12:20 UTC, CyberDem0n commented on patroni/ctl.py
> +﻿'''
There is some unwanted character:
```
@@ -1,4 +1,4 @@
-'''
+<U+FEFF>'''
 Patroni Control
 '''
```
```suggestion
'''
```

2020-09-15 12:20 UTC, CyberDem0n commented on requirements.txt
> +﻿urllib3[secure]>=1.19.1,!=1.21
There is some unwanted character:
```
diff --git a/requirements.txt b/requirements.txt
index 5c30d3a..36cbae8 100644
--- a/requirements.txt
+++ b/requirements.txt
@@ -1,4 +1,4 @@
-urllib3[secure]>=1.19.1,!=1.21
+<U+FEFF>urllib3[secure]>=1.19.1,!=1.21
```

```suggestion
urllib3[secure]>=1.19.1,!=1.21
```

2020-09-15 13:21 UTC, CyberDem0n requested changes
Unfortunately unit-tests are failing, therefore more changes are necessary (see comments).
And tests:
```diff
diff --git a/tests/test_ctl.py b/tests/test_ctl.py
index e63da17..d93c5d1 100644
--- a/tests/test_ctl.py
+++ b/tests/test_ctl.py
@@ -561,7 +561,7 @@ class TestCtl(unittest.TestCase):
         self.assertRaises(PatroniCtlException, apply_config_changes, before_editing, config, ['a'])

     @patch('sys.stdout.isatty', return_value=False)
-    @patch('cdiff.markup_to_pager')
+    @patch('patroni.ctl.markup_to_pager')
     def test_show_diff(self, mock_markup_to_pager, mock_isatty):
         show_diff("foo:\n  bar: 1\n", "foo:\n  bar: 2\n")
         mock_markup_to_pager.assert_not_called()
@@ -570,6 +570,9 @@ class TestCtl(unittest.TestCase):
         show_diff("foo:\n  bar: 1\n", "foo:\n  bar: 2\n")
         mock_markup_to_pager.assert_called_once()

+        with patch('patroni.ctl.find_executable', Mock(return_value=None)):
+            show_diff("foo:\n  bar: 1\n", "foo:\n  bar: 2\n")
+
         # Test that unicode handling doesn't fail with an exception
         show_diff(b"foo:\n  bar: \xc3\xb6\xc3\xb6\n".decode('utf-8'),
                   b"foo:\n  bar: \xc3\xbc\xc3\xbc\n".decode('utf-8'))
```

2020-09-15 13:21 UTC, CyberDem0n commented on patroni/ctl.py
> +    import cdiff as ydiff
```suggestion
try:
    from ydiff import markup_to_pager, PatchStream
except ImportError:  # pragma: no cover
    from cdiff import markup_to_pager, PatchStream
```

And please move it after the `from six.moves.urllib_parse import urlparse`

2020-09-15 13:21 UTC, CyberDem0n commented on patroni/ctl.py
> +        ydiff.markup_to_pager(ydiff.PatchStream(buf), opts)
```suggestion
            if find_executable('less'):
                pager = None
            else
                pager = 'more.com' if sys.platform == 'win32' else 'more'
            pager_options = None

        markup_to_pager(PatchStream(buf), opts)
```

2020-09-15 14:08 UTC, CyberDem0n approved these changes

2020-09-15 14:18 UTC, CyberDem0n commented
@mbanck, @df7cb this is sort of a "breaking" change, because there is no `python3-ydiff` package available.
A couple of years ago `cdiff` was renamed to `ydiff` and therefore no longer maintained.
In fact, interfaces didn't change much and patronictl will happily continue to work with `python3-cdiff`, so I believe it shouldn't become a big issue for you.

2020-09-16 11:43 UTC, sdudoladov commented
:+1:

2020-09-16 13:21 UTC, CyberDem0n commented
:+1:

2020-09-16 13:21 UTC, merged