Fixes in `patroni.request`
zalando/patroni pull request #2768
Opened 2023-07-21 09:33 UTC by CyberDem0n

1.  Take client certificates only from the `ctl` section. Motivation: sometimes there are server-only certificates that can't be used as client certificates. As a result neither Patroni not patronictl work correctly even if `--insecure` option is used.
2. Document that if `restapi.verify_client` is set to `required` then client certificates **must** be provided in the `ctl` section.
3.  Add support for `ctl.authentication` and prefer to use it over `restapi.authentication`.
4. Silence annoying InsecureRequestWarning when `patronictl -k` is used, so that behavior becomes is similar to `curl -k`.

2023-07-24 08:47 UTC, hughcapet commented on docs/ENVIRONMENT.rst
> +    - If you enabled client certificates validation (``PATRONI_RESTAPI_VERIFY_CLIENT`` is set to ``required``), you also **must** to provide **valid client certificates** in the ``PATRONI_CTL_CERTFIL
```suggestion
    - If you enabled client certificates validation (``PATRONI_RESTAPI_VERIFY_CLIENT`` is set to ``required``), you also **must** provide **valid client certificates** in the ``PATRONI_CTL_CERTFILE``, ``PATRONI_CTL_KEYFILE``, ``PATRONI_CTL_KEYFILE_PASSWORD``. If not provided, Patroni will not work correctly.
```

2023-07-24 09:23 UTC, hughcapet commented on patroni/request.py
> +        * ``cert``, ``key`` and ``key_password`` are configured if ``ctl -> certile`` is available.
```suggestion
        * ``cert``, ``key`` and ``key_password`` are configured if ``ctl -> certfile`` is available.
```

2023-07-24 17:36 UTC, barthisrael requested changes
Overall looks good. Just some small comments.

2023-07-24 17:36 UTC, barthisrael commented on typings/urllib3/poolmanager.pyi
> +from typing import Any, Dict, Optional, Type
```suggestion
from typing import Any, Dict, Optional
```

I couldn't find any reference to `Type` in that file.

2023-07-24 17:36 UTC, barthisrael commented on typings/urllib3/poolmanager.pyi
> +from .connectionpool import HTTPConnectionPool
```suggestion
```

I think this one is not needed here either.

2023-07-25 06:45 UTC, hughcapet commented
👍

2023-07-25 06:47 UTC, CyberDem0n commented
:+1:

2023-07-25 06:48 UTC, merged