Don't return logical slots for standby cluster
zalando/patroni pull request #2816
Opened 2023-08-16 09:41 UTC by CyberDem0n

Cluster.get_replication_slots() didn't take into account that there can not be logical replication slots in a standby cluster replicas. It was only skipping logical slots for the standby_leader, but replicas were expecting that they will have to copy them over.

Also on replicas in a standby cluster these logical slots were falsely added to the `_replication_slots` dict.

2023-08-16 13:49 UTC, matthbakeredb requested changes
Looks good, small formatting, comment suggestions

2023-08-16 13:49 UTC, matthbakeredb commented on patroni/dcs/__init__.py
> +            Node that is not supposed to become a leader (nofailover) will not have permanent replication slots.
```suggestion
            A node that is not supposed to become a leader (*nofailover*) will not have permanent replication slots.
```

2023-08-16 13:49 UTC, matthbakeredb commented on patroni/dcs/__init__.py
> +            In a standby cluster we support only physical replication slots.
```suggestion
            In a standby cluster we only support physical replication slots.
```

2023-08-16 13:49 UTC, matthbakeredb commented on patroni/dcs/__init__.py
> +            to show a warning if they are not supported by PostgreSQL before v11.
```suggestion
            The returned dictionary for a non-standby cluster always contains permanent logical replication slots in
            order to show a warning if they are not supported by PostgreSQL before v11.
```

2023-08-16 13:49 UTC, matthbakeredb commented on patroni/postgresql/__init__.py
> +            # standby cluster can't have logical replication slots and we don't need to enforce hot_standby_feedback
```suggestion
            # Standby cluster can't have logical replication slots, and we don't need to enforce hot_standby_feedback
```

2023-08-16 13:49 UTC, matthbakeredb commented on patroni/postgresql/slots.py
> +        # slots to be copied from the primary should be removed from the structure,
```suggestion
        # Slots to be copied from the primary should be removed from the *slots* structure,
```

2023-08-16 13:49 UTC, matthbakeredb commented on patroni/postgresql/slots.py
> +                    is_standby_cluster=self._postgresql.global_config.is_standby_cluster, show_error=True)
```suggestion
                    self._postgresql.name,
                    self._postgresql.role,
                    nofailover,
                    self._postgresql.major_version,
                    is_standby_cluster=self._postgresql.global_config.is_standby_cluster,
                    show_error=True,
                )
```

2023-08-16 14:04 UTC, barthisrael approved these changes
Looks good to me too.

2023-08-16 14:08 UTC, CyberDem0n commented on patroni/dcs/__init__.py
> +    def get_replication_slots(self, my_name: str, role: str, nofailover: bool, major_version: int, *,
I changed the order of the arguments with default values and it took me some time to figure out why tests are failing, while linting didn't found any problem.

2023-08-16 14:24 UTC, barthisrael commented on patroni/dcs/__init__.py
> +    def get_replication_slots(self, my_name: str, role: str, nofailover: bool, major_version: int, *,
Ah, cool then, thanks!

2023-08-16 14:38 UTC, matthbakeredb commented on patroni/postgresql/slots.py
> +                    is_standby_cluster=self._postgresql.global_config.is_standby_cluster, show_error=True)
The goal is not to keep the code shorter using less space but for me to easily discern between args. It's easier on my eye to scan down a list than to read horizontally with mixed breaks in dividing spaces.

btw I thought this looked a little messy and ran black on it and this was the result.

2023-08-16 14:38 UTC, matthbakeredb commented on patroni/dcs/__init__.py
> +    def get_replication_slots(self, my_name: str, role: str, nofailover: bool, major_version: int, *,
In $previous_job we had a local rule that all methods should be explicitly called with full keyword args to ensure that if the signature changed in the called method the calling code wouldn't start sending an input to the wrong place.

2023-08-18 10:35 UTC, hughcapet commented
👍

2023-08-18 11:36 UTC, CyberDem0n commented
:+1:

2023-08-18 11:36 UTC, merged