Introduce a dedicated postgres connection for REST API
zalando/patroni pull request #2833
Opened 2023-08-24 14:22 UTC by CyberDem0n

Sharing a single connection between REST API and the main thread (doing heartbeats) was working mostly fine, except when Postgres becomes so slow that REST API queries start blocking the main loop.

If the dedicated REST API connection isn't available we use the heartbeat connection as a fallback.

2023-08-25 11:04 UTC, matthbakeredb requested changes
Looks good. One tiny correction.

2023-08-25 11:04 UTC, matthbakeredb commented on patroni/api.py
> +        # We first try top get a heartbeat connection because it is always required for the main thread
```suggestion
        # We first try to get a heartbeat connection because it is always required for the main thread.
```

2023-09-01 11:36 UTC, barthisrael approved these changes

2023-09-04 05:33 UTC, hughcapet commented on tests/test_api.py
> +            self.srv.query('SELECT 1')
Maybe something like 
```
self.assertEqual(self.srv.query('SELECT 1'), MockConnection.query('SELECT 1'))
```
or
```
        with patch.object(MockConnection, 'get', Mock(side_effect=[MockConnect(), OperationalError])), \
             patch.object(MockConnection, 'query') as mock_query:
            self.srv.query('SELECT 1')
            mock_query.assert_called_once_with('SELECT 1')
```
?

2023-09-04 20:32 UTC, hughcapet commented
👍

2023-09-05 05:26 UTC, CyberDem0n commented
:+1:

2023-09-05 05:26 UTC, merged