Don't start stopped postgres in pause
zalando/patroni pull request #2848
Opened 2023-09-04 08:31 UTC by CyberDem0n

Due to a race condition Patroni was falsely assuming that the standby should be restarted because some recovery parameters (primary_conninfo or similar) were changed.

Close https://github.com/zalando/patroni/issues/2834

2023-09-04 13:23 UTC, matthbakeredb requested changes
Seems good, couple small suggestions.

2023-09-04 13:23 UTC, matthbakeredb commented on patroni/postgresql/config.py
> +                * `postgresql.auto.conf`
```suggestion
                * ``postgresql.conf``;
                * ``postgresql.auto.conf``;
```

2023-09-04 13:23 UTC, matthbakeredb commented on patroni/postgresql/config.py
> +                    and self._postmaster_ctime != postmaster_ctime:
```suggestion
            if all(isinstance(exc, PostgresConnectionException),
                   self._postgresql_conf_mtime == pg_conf_mtime,
                   self._auto_conf_mtime == auto_conf_mtime,
                   self._passfile_mtime == passfile_mtime,
                   self._postmaster_ctime != postmaster_ctime):
```

2023-09-05 05:21 UTC, CyberDem0n commented
:+1:

2023-09-06 05:23 UTC, hughcapet commented
👍

2023-09-06 06:57 UTC, CyberDem0n commented
:+1:

2023-09-06 06:57 UTC, merged